### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by prolic** [proophsoftware/es-emergency-call#3]
Let's say we have an event-sourced online-shop and we want to provide a plugin-system like in magento. From the admin interface you can select plugins and install them to your shop with a mouse-click. How can such a plugin system be implemented with an event sourced aggregate root? What are the limitations?

Things to consider:
- Add more properties to an aggregate root (f.e. product), see also https://github.com/proophsoftware/es-emergency-call/issues/2
- Add custom events
- Add custom commands
- Update existing projections (maybe because of new properties we want to customize product projector and restart it)
- Add new projections
- Customize view templates (not really a DDD question, however...)
- Custom JS added, changed
- Anything else I forgot to mention

Of course sometimes things need manual intervention, however I would be curious (without urgent need!), how such a plugin system could look like.

**Comment by codeliner** [comment]
You need to keep the open/closed principle in mind and design your system carefully.

First question here is what is the goal of the event-sourced online shop? Do you want to offer it as Paas so you have control over the installation and also over the plugins or do you want to provide an on-premise solution that users can download as an open source package and install or do with the system whatever they want?

**Comment by prolic** [comment]
More like the latter, install and do whatever you want to. Also this is more a hypothetical question.

**Comment by codeliner** [comment]
ok, for a monolith you need a good web framework like ZF or Sf that supports modules. Each plugin should be a module and you have to use a configuration-driven approach:
- each module/plugin could provide prooph/service-bus routing to listen on events and provide new commands etc.
- you can use prooph's plugin system for service-bus and event-store to enrich messages, route them to other handles, listeners, process managers ....

You could also provide the possibility to extend from core aggregates to add new behavior or change existing. But I can imagine that this would get messy very quickly so I would not allow this (mark all aggregates as final class). Same applies for projections. Add new ones ok, modify existing ones: meh

A well designed plugin API should be enough. If someone needs to modify core logic they would be better of with an own solution rather than messing around with an application that does not fit well with their use cases.

Anyway, like mentioned by @sandrokeil in the chat: this kind of projects have problems with modern infrastructure. I would not use a monolith but instead design services that provide APIs:
- Messagebox for commands
- GraphQL for queries
- event-stream http API/Webhooks based on events to allow other services to react on important changes

I think this is the new way of designing modular services. The core can be hosted in the cloud (on-premise still possible) and extensions can be added as new services using the APIs provided by the core services and other plugin services.

**Comment by prolic** [comment]
:+1: 

I will close this for now, maybe when it's time to write something like this, I'll keep you updated on newer developments.
