### ISSUE TITLE
Slow import

### ISSUE THREAD

**Issue by enumag** [proophsoftware/es-emergency-call#5]
Currently we're trying to import data from the previous system to the new one we're working on. The new system is using Prooph so basically during the import we're generating prooph commands and let the system handle them.

The problem is that the import is currently very slow. In this issue I'd like to discuss the reasons why it is so slow and how to make it faster. I used [blackfire](https://blackfire.io) to profile it so I do have some good information.

Here is the main loop of the import:

```php
foreach ($generator->generateCommands() as $command) {
	$this->commandBus->dispatch($command);
	$this->mainProjector->project();
}
```

The main problem seems to be the `project` call which essentially calls `Prooph\EventStore\Pdo\Projection\PdoEventStoreReadModelProjector::run()`. Next I want to discuss why we believe we need to call the projections here and why is it so damn slow.

Why we call projections after each command?
----

It's simply because without the projections being up-to-date the following commands would fail. In some cases the command handlers call projections to verify if some ID exists in the database. You might argue that this should be verified using the EventStore but we can't use that in cases where the ID we need to check belongs to a different bounded context which is sometimes the case.

Example:
- One bounded context is ContactManagement where we store the necessary information about people and companies.
- These contacts can be referenced in several other bounded contexts (for various different purposes). For example we have a bounded context where we store Contracts between some of those people.
- This means that the AddContractCommand holds IDs of 2 contacts from ContactManagement. Obviously we have to verify that the IDs indeed exist in the database and that they are eligible to be contractors.
- Since the contacts are in different bounded context than contracts, we can't load them from EventStore. So we ask the main projection for the contacts.

Now does this sound ok to you or not? Would you recommend any changes?

I have a feeling that the command handlers should better not need any data from projections or from different bounded contexts. Do you agree or disagree with that? (I'm not quite sure how to achieve that in this case though.)

Why is `PdoEventStoreReadModelProjector::run()` slow?
----

The projections are slow simply because of [this line](https://github.com/prooph/pdo-event-store/blob/1619c18c18093b537e5f607bd399b7568ab8c3a1/src/Projection/PdoEventStoreReadModelProjector.php#L448). It causes a SQL select to every event stream in the database every time we run the projections - which is after each command as seen above in the main loop.

Quite obviously this is to check if there are any new events in each event stream so that they can be projected. **But of course this causes a LOT of unnecessary selects because most streams don't have any new events. Most of the time there is only one stream that has a new event. This is a serious performance bottleneck.**

Because of this I have a feeling that we might not be using the best EventStore implementation. We're not locked to Postgres or PDO for the EventStore. Can you recommend a different implementation that doesn't need so many unnecessary selects on the underlying database?

**Comment by basz** [comment]
We're in exactly the same position as you are.

So one tip I can give to speed things up is to precalculate id's. Thus avoiding the lookup in projections. How? We utilize Uuid::uuid5 which will generate the same uuid given a namespace and a name.

for example
```
$catalogueId = CatalogueId::generate(sprintf('%s.catalogue-id', $legacyCatalogueId));
```
$catalogueId will now be consistent and do not need to be lookup'd but can be reused across commands.

**Comment by enumag** [comment]
@basz I think you misunderstood the problem...

**Comment by enumag** [comment]
Note: We're using the strategy where each aggregate has its own stream. So we have as many streams as we have aggregates. I was under the impression that this was the recommended strategy despite the fact that it creates MANY sql tables. Is that correct?

Checking the streams one by one in `PdoEventStoreReadModelProjector` is simply a no-go when you can easily have a million streams or more. It is too slow even for normal usage - it would take too long before the projector would find new events.

**Comment by sandrokeil** [comment]
Can you not use a dedicated projection (own CLI) which calls `$this->mainProjector->project();`?  Maybe you can setup a [dedicated stream projector](http://docs.getprooph.org/event-store/standard_projections/overview.html#3-5-1) and listen on this stream. Anyway, I guess you have to split your workflow into multiple PHP processes.

If your command fails due missing ID in read model, you can also wait a second and make a retry.

**Comment by codeliner** [comment]
> Now does this sound ok to you or not? Would you recommend any changes?

The approach is ok, but handling everything in a sequence is of course the slowest option. Anyway, you should always start with the simplest solution and it seems that you've done exactly that, so nothing wrong about it.

Regarding projection performance: @basz and @sandrokeil already gave some tips. 
What stream strategy are you using? OneStreamPerAggregate? 
I'm asking because SingleStreamStrategy maybe combined with a stream per aggregate type is the better option.

**Comment by prolic** [comment]
@enumag 

I have some ideas how to have much better performance for projections using one-stream-per-aggregate, but this will require a new major release and a lot of additional work. So maybe this will come at the end of this year (earliest).

As for now, you have a few options:
- leave it as is... as a legacy data import usually occurs only once, you can simply don't care about how long it takes (at least when it's below a year, lol)
- switch to single-stream-strategy (but I get why you may want one-stream-per-aggregate)
- don't use the projection manager but event-bus to dispatch events, so they come at the projection directly, no need to query anything, for replaying you would need a dedicated replay script, because you cannot simply reset the projection - this approach can be combined with amqp really good
- you can use http-event-store-api to create projections (and not the projection manager), thanks to async http requests with curl, you can query multiple streams at the same time (thus having at least some treading in play)
- you can do something quite tricky: use the event-bus for initial import, while creating the stream position data the projection would have had yourself. then you can insert an entry into your db and claim this is the work of the projection. you disable the event-bus and run with projections from there.

Have you considered https://github.com/prooph/standard-projections/blob/master/docs/projections.md ?

**Comment by enumag** [comment]
@sandrokeil I didn't really like the wait & retry workflow but I'll consider it.

@codeliner Yeah I'll probably split the import to seveal parallel processes later on, I just wanted something simple at first and noticed the performance issue in prooph.

> What stream strategy are you using?

Yeah we were using OneStreamPerAggregate and that's what was causing the problem. I've changed it to SingleStreamStrategy just now and the import is indeed much faster (minutes instead of hours).

@prolic

> leave it as is... as a legacy data import usually occurs only once, you can simply don't care about how long it takes (at least when it's below a year, lol)

Not possible. We have a lot of data to import and writing the code to import everything will take months. We need to run the import over and over as we add code for more data. There will only be one import in the end of course but while testing it we'll be running it a lot.

> switch to single-stream-strategy (but I get why you may want one-stream-per-aggregate)

Yeah, I've done that for now. I'll probably switch back to OneStreamPerAggregate when it becomes usable.

The rest of your suggestions are a bit more complicated and will take some time to consider. I'll have a look into standard projections too.

----

Thanks everyone for your comments and ideas.

I think we need to address this in the documentation. Currently it [says](http://docs.getprooph.org/event-store/implementations/pdo_event_store/variants.html#3-2-1-2-5-1) that AggregateStreamStrategy is the most performant of all which is clearly not the case. It might be the fastest for inserting but it's currently so slow for projections that it is impossible to use it in production environment.

**Comment by prolic** [comment]
@enumag see https://github.com/prooph/pdo-event-store/pull/136
