### ISSUE TITLE
Process manager and projections problem

### ISSUE THREAD

**Issue by enumag** [proophsoftware/es-emergency-call#6]
Looks like I have a problem with one of the more complicated parts of our system. Since it seems like something that could happen in other systems as well I'll try to ask here to hopefully reach some proper solution.

### The relevant part of the domain

The company (which owns the application) has some clients. Every month the system generates some fees which the clients are supposed to pay. Later on the client payments are imported into the system.

About once a month an admin clicks a button to process all the fees and payments and pair them (to see which fee is covered by which payment). It is not enough to just calculate account ballance, we really need the pairing to know when the client payed which fee. (Of course some payment may cover multiple fees or one fee can be covered by multiple payments. That's not really important for this issue.)

In some cases the fees can be negative which means the company is supposed to send some money back to the client.

Some of the payments can be outgoing payments which means the company sent some money back to the client.

### The pairing process

Now when the admin clicks the button, here is a pseudo-code of what should happen:

```
var clients = findAllClients()

foreach (clients as client) {
    payments = findPaymentsSentByTheCompanyToTheClient(client)
    fees = findClientsNegativeFees(client)

    allocate(payments, fees)

    convertRemainingNegativeFeesToVirtualIncomingPayments(fees)
    convertRemainingOutgoingPaymentsToVirtualFees(payments)

    payments = findPaymentsSentByTheClient(client)
    fees = findClientsNormalFees(client)

    allocate(payments, fees)
}
```

Explanation of `convertRemainingNegativeFeesToVirtualIncomingPayments(payments)`:

There is an unpaired negative fee which means the company should have sent some money to the client but didn't do so. In this case we convert the negative fee to a virtual incoming payment and use it to cover the normal fees of the client.

Explanation of `convertRemainingOutgoingPaymentsToVirtualFees(payments)`:

There is an unpaired outgoing payment which means the company sent some money to the client by accident (or sent more than it should have). In this case we convert the payment to a new fee, essentially asking the client to send the money back.

### The implementation

When the admin clicks the button, it triggers some command (`AllocatePaymentsToFeesCommand`). There is no aggregate for this so the command handler just creates an event (`PaymentAllocationsRequested`) and runs it into EventBus. The event is then consumed by a process manager.

This process manager basically has the pseudocode from above. The `convertRemainingNegativeFeesToVirtualIncomingPayments`, `convertRemainingOutgoingPaymentsToVirtualFees` and `allocate` parts are all generating some new commands which are then dispatched to the command bus.

Does this make sense so far? If you'd recommend any changes based on what I wrote above, please tell me.

### The problem

The issue we're facing is that the new virtual payments and fees from the convert* parts should also be processed by the last part of the process manager. This of course won't be the case now because the find* functions are searching the projections which were not yet updated to contain these new virtual payments and fees - the commands to create them were dispatched just above and didn't have time to go through the entire command->handler->aggregate->event->projection process.

Can you give me some ideas how to solve cases like these when the process manager cannot continue because projections are not up to date? I think I missed some important lesson on how to implement a process manager...

**Comment by basz** [comment]
3 possible *thoughts*

I believe a Process Manager responds to event data *only*, can have *any* side effect including dispatching *additional* commands. Using read models might be fine, but see my comment below

So I think ideally your PM should listen to the `PaymentAllocationsRequested` event only to dispatch new commands. Those commands will eventually emit new events that the PM should also subscribe to. I'm assuming those events have the necessary data on them. You could be able to do your calculations then.

If those events do not have the needed data the PM could need an *internal* state that it needs to keep persisted somehow. One way of getting here is by turning the PM into an Aggregate itself and you would have an object with relevant and up-to-date state.

A more pragmatic route I can think of is simply waiting a bit after the dispatch so read models can catch up. This will only work when your architecture is asynchronous in nature and may not be acceptable to the business (since the subject is real money here, business owners might not like when incorrect billing occurs).
To do this I would split your main loop into two loops (first dispatch all commands, then wait, then loop again to do your final calculations).

disclaimer: This is all theory for me I've never actually done this at this time but I'm interested in this kind of problem. I might be just blahing here :-) (someone please slap, uh, correct me)

**Comment by enumag** [comment]
@basz If I go that way then the problem is *how long should I wait?* How can I be certain that I can safely continue?

**Comment by codeliner** [comment]
@basz theory is good :+1: 

@enumag Can you provide a [draw.io](https://www.draw.io/) diagram that illustrates the process?

- Start with the Admin clicking on the button
- Try to focus on events:
    - What happens when? 
    - What should happen in a sequence? 
    - What can go wrong?

The diagram does not need to be perfect, Just good enough that one can understand the problem quickly by only looking at the diagram.

**Comment by basz** [comment]
How about 5 times 2 seconds. Still not safe enough. arg... There simply is no way you can absolutely be sure read models are up-to-date. So if your business owners insist on consistency depending on read models simply won't work (all the time).

> @basz theory is good 👍

phew...

**Comment by codeliner** [comment]
Export as xml from draw.io and put it in a gist. Link the gist here so we can work on it while discussing the problem

**Comment by codeliner** [comment]
@basz 
> There simply is no way you can absolutely be sure read models are up-to-date.

Nah, you can monitor projections (credits @bweston92)


![image](https://user-images.githubusercontent.com/5131987/43519530-1a2d036e-9590-11e8-8952-eb6325089ec4.png)


You can also work with correlationIds and include them in the read model or store the last processed event id(s)/event stream positions in the projection and compare it with the event in the process manager.
A lot of options, but a better understanding of the problem is required first.

**Comment by enumag** [comment]
@codeliner I never worked with draw.io so I'm not exactly sure what the diagram should look like. Can you give me some example diagram I could use for reference what you want? What diagram template should I choose?

**Comment by codeliner** [comment]
take the blank diagram and work with basic shapes like rectangle, arrows, text and colors.
No special layout required. Imagine you're next to a whiteboard and want to use it to explain me the problem. I'm listening and watching and ask questions if I don't understand ;)

**Comment by enumag** [comment]
@codeliner I tried to draw a diagram. Hopefully it is what you wanted...

There isn't really anything that can go wrong during the process other than incorrect pairing (due to missing fees or payments in the query results) which I need to prevent from happening. Meaning there are no business events indicating a failure.

Some payments or fees could stay unallocated but we don't need an event for that. They will simply be allocated the next time.

(click the open with draw.io button)
https://drive.google.com/file/d/14jVeozG8_CNnpmYsuF-qVrSrBg4QYtU4/view

**Comment by codeliner** [comment]
thx @enumag 
exactly what I was looking for :+1: 

Here is another draw.io diagram: https://gist.github.com/codeliner/97ef981147a95a3096c7c89d6dd3d32c

Let me know if it helps!

**Comment by enumag** [comment]
@codeliner At a glance it does make sense but I think I need to try to write it down in my own words to see if I understand it correctly. Can you confirm if I got it right please and answer the bold parts where I'm not sure?

If I got something wrong then you can skip everything below that point because I most likely need to rethink everything after that.

First line of the diagram (+ the process manager below it):

1. The PaymentAllocationsAggregate seems to be something that oversees the entire process. A new aggregate gets created by the RequestAllocationsCommand and then this single aggregate oversees everything for all clients. - correct?

**EDIT: Maybe there should be a separate PaymentAllocationsAggregate instance for each client? I'm not sure. But then the single RequestAllocationsCommand would cause multiple aggregates to be created, not sure if that's good or not.**

2. So in the RequestAllocationsCommandHandler I should select the negative payments and fees for all clients and send them to the PaymentAllocationsAggregate which would then produce one PaymentAllocationsRequested event for each client? This aggregate would hold the state of all the given fees and payments - at this point all of them would be unallocated.

3. The AllocatePaymentProcessManager would process one PaymentAllocationsRequested event at the time, pair the fees and payments from that event and dispatch several AllocatePaymentCommands. **This is where I'm unsure because your diagram only has one AllocatePaymentCommand there.**

Second line of the diagram:

4. AllocatePaymentCommands would be then processed by the PaymentAggregate. The NotifyPaymentAllocationsProcessManager would then notify the PaymentAllocationsAggregate about the change.

5. I'm guessing I should also add another process manager to notify the FeeAggregate about the new allocation? FeeAggregate does need to know if the fee is allocated or not, some actions are locked after allocation.

Third line of the diagram:

6. Here is where it gets tricky. I don't see a way for the PaymentAllocationsAggregate to tell if it already got all the notifications it should expect and can produce the next event. Remember that step 1 won't allocate all payments if there are not enough fees.

... Thinking about it more there might actually be a way. Let's take one client. At the end of step one either all of the client's negative fees or all of the payments sent by the company to the client should be allocated. So when either of the two collections (or both) is fully allocated we can continue to the next step for that client. Does that sound correct? I'm slightly worried about some future edge case causing neither the fees or payments to be fully allocated after step 1. There is no such case now though so I'm not sure what the circumstances would be.

**EDIT: An edge case that comes to mind is if the PaymentAllocationsAggregate receives no payments or no fees for a client. I'm guessing in that case it should produce a Step1CompletedEvent right away, skipping the PaymentAllocationRequestedEvent. After all it would not receive any notifications later so this is the only time to do it.**

If everything I wrote is correct, I believe I should be able to implement the other steps based on this.

Thank you very much for your work on this problem. It never occurred to me to split the one process manager to multiple, adding a new aggregate and a bunch of new events. It will be a lot of work of course but it certainly looks like the correct way to think about such cases.

I think it would be useful for other people to have an example like that so maybe I'll try to write an article based on this.

----

Still the PaymentAllocationsAggregate waiting for the notifications worries me a little. Even if the axioms about the process allow it to work in this case, what can we do in other use cases when there is no way for the aggregate to tell if it already got all the notifications? I fully expect you to not be able to answer this without a specific use-case though so the answer is most likely "when it happens, go back to the drawing board".

**Comment by enumag** [comment]
One more thing. Where should the actual logic of which payment gets allocated to which fee be implemented? The PaymentAllocationsAggregate? Or the AllocatePaymentProcessManager? In what I wrote above I thought it would be the AllocatePaymentProcessManager but I now think you actually meant for the logic to be in the PaymentAllocationsAggregate and for the PaymentAllocationRequested command to hold the actual allocation data (PaymentId, FeeId, amount) - that would explain my confusion about AllocatePaymentProcessManager only producing one AllocatePaymentCommand.

**Comment by enumag** [comment]
Still though the problem with projections not being up to date still exists here. If I go with the saga from your diagram and let it go through steps 1 and 2 then the PaymentAllocationsAggregate will decide that step 3 can be started but there is no guarantee that all events from step 2 were already projected so step 3 could still be started with wrong data.

That's not to say I don't like your solution, I think it improved my thought process about such problems significantly. But it doesn't seem to solve the problem that lead me to create this issue in the first place...

**Comment by codeliner** [comment]
:tada: Your assumptions are perfect. Exactly what I wanted to explain. I'm really happy about the result. Thx for collaboration @enumag 

I comment on a few things to underline the concept and answer your bold questions:

> A new aggregate gets created by the RequestAllocationsCommand and then this single aggregate oversees everything for all clients.

Correct! You can think of the `PaymentAllocations` aggregate being the MAIN PROCESS. It's task is to spawn sub processes (using `PaymentAllocationRequested` events) and track the progess of each of the sub processes (`Payment` and `Fee` aggregates).

Ever wondered why a **ProcessManger** is called a ProcessManager? Now you have the answer. It's because aggregates are (business) processes and process managers are like users. Instead of a user clicking on a button to trigger next action you have a litte **function** sitting around in your infrastructure and waiting for an event to trigger next action of a process.
The actual work is done in the aggregates but only one step at the time. If the entire process should not be observed and managed by a user, then you need those process manager to automate processing. 

As you can see, I've used multiple process managers in the diagram. Each **reaction** to an event is handled with a dedicated **stateless and side-effect free function**. Those functions can be part of a single process manager class OR you have a class with a single `__invoke()` function for each. That's implementation detail.

> Maybe there should be a separate PaymentAllocationsAggregate instance for each client?

Maybe yes, maybe no ;). Those are the things you need to explore. Maybe you start with a single aggregate and recognize later that one for each client would be better. If that's the case then you have to refactor. To avoid loosing too much time during model exploration phase, try to draw different diagrams and get a feeling for the model. If that is not enough, there is also [Event Machine](https://github.com/proophsoftware/event-machine) which can be used to prototype ideas. A litte bit practice with Event Machine and you're able to build a working prototype of your problem described here within a day. Not a perfect production ready model, but a model that works good enough to try it out and play with it. Event Machine has out-of-the-box SwaggerUI integration, so you can easily interact with your prototype and see the results in the event store, read models, etc.
Next day you start from scratch and try another idea. Prototyping model design can save you a lot of time later. 

> and dispatch several AllocatePaymentCommands. This is where I'm unsure because your diagram only has one AllocatePaymentCommand there.

Correct! Do you see the litte **foreach** after the first process manager. I used it to illustrate what you've described.

> I'm guessing I should also add another process manager to notify the FeeAggregate about the new allocation?

Yes! Good idea.

> There is no such case now though so I'm not sure what the circumstances would be.

Don't worry about the future. Greg Young did a great talk about that topic: https://vimeo.com/108441214

> An edge case that comes to mind is if the PaymentAllocationsAggregate receives no payments or no fees for a client. I'm guessing in that case it should produce a Step1CompletedEvent right away, skipping the PaymentAllocationRequestedEvent. After all it would not receive any notifications later so this is the only time to do it.

Sounds good.

> I think it would be useful for other people to have an example like that so maybe I'll try to write an article based on this.

Definitely! I think we did a good job here to discover a possible solution. Summarizing this in a blog post along with a demo implementation would be really useful. 

> what can we do in other use cases when there is no way for the aggregate to tell if it already got all the notifications? 

Yeah, go back to the drawing board is always the best idea. What you can do is: you can monitor the aggregate. This idea is again borrowed from process management. If you have a critical process it's often a good idea to set up a supervisor that monitors the process and takes actions in case of unwanted events. 

For the `PaymentAllocations` aggregate a supervisor (a php script running in the background) could periodically check aggregate state and see if notifications are missing for too long. The php script could send an email to the developers and tell them about the problem. Compare that with an exception written to a log file and parsed by log parser that sends an email for each exception found.

**Comment by enumag** [comment]
@codeliner Thanks for the answer and the tips! Still though I'm missing an answer for [this comment](https://github.com/proophsoftware/es-emergency-call/issues/6#issuecomment-409849901) and [this comment](https://github.com/proophsoftware/es-emergency-call/issues/6#issuecomment-409852403) which are important.

Another thing that comes to mind is **why wait for the notifications from step 1 before starting step 2?** The aggregate already has everything it needs for step 2 when it generates the PaymentAllocationRequested events so it could also generate the step 2 events PaymentToFeeConversionRequested / FeeToPaymentConversionRequested right away without waiting for step 1 notifications. Is that a good idea or not?

**Comment by codeliner** [comment]
> but there is no guarantee that all events from step 2 were already projected so step 3 could still be started with wrong data.

Use the events for communication. They are your single source of truth and the trigger for the next process step.

**Comment by codeliner** [comment]
> One more thing. Where should the actual logic of which payment gets allocated to which fee be implemented? The PaymentAllocationsAggregate?

Yes, business logic should be handled in an aggregate. The process manager is "dumb", it just knows enough to dispatch next command.

**Comment by enumag** [comment]
>> but there is no guarantee that all events from step 2 were already projected so step 3 could still be started with wrong data.
>
> Use the events for communication. They are your single source of truth and the trigger for the next process step.

That's not very useful to be honest... I discussed it further with my colleague @tomcizek and he suggested an idea. Maybe you meant the same thing?

His advice was to not wait until the data form step 2 are in projections before starting step 3 because the PaymentAllocationsAggregate has the data from step 2 anyway. **This would mean that the aggregate would have to merge the input fees/payments for step 3 from read model with the new fees/payments generated in step 2.** This is a little difficult because the fees are firstly ordered by date and also grouped by both date and by priority so the data structure is way more complicated than a simple list of fees. (I significantly simplified things for the purpose of this issue.) Still although it would be non-trivial it's definitely doable.

Is this what you meant by using the events?

**Comment by codeliner** [comment]
> His advice was to not wait until the data form step 2 are in projections before starting step 3 because the PaymentAllocationsAggregate has the data form step 2 anyway. 

Yes, that's what I suggest. The aggregate manages its internal state (by recording and applying new events) so it should have all information it needs to protect invariants: "Step 3 can only be started if all sub processes from step2 are completed"

**Comment by codeliner** [comment]
> why wait for all the notifications from step 1 before starting step 2?

As described above: this is model exploration. If it's possible to handle steps in parallel then do it. I don't know the domain weill enough to give concrete advice here. Would need to try it myself first and ask a lot more questions ;)

**Comment by enumag** [comment]
Yeah, makes sense. I think I'll change it that way then. It should simplify things quite a bit and I don't see any downsides for our case. And if we do find some problem later it would not be too difficult to change it.

With this I consider this issue solved. As a TL;DR I'd sum it as this:

- A complex automated process should have it's own aggregate root to oversee it.
- A process manager should not make any decisions, it should receive everything it needs to create the command in the event. The logic should be done in the aggregate root.
- More process managers might be needed for the other aggregates to notify the overseer that they received the events.
- This setup also allows to easily solve problems when the overseer can't continue the process on it's own and requires a human to make some decisions during the process.

Do you consider that summary correct, @codeliner?

**Comment by codeliner** [comment]
Perfect @enumag :+1:
